"""Replace location with code in warehouses

Revision ID: 03e8f6665ddb
Revises: 1940de7a4bf4
Create Date: 2024-10-02 12:09:18.352800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e8f6665ddb'
down_revision = '1940de7a4bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_warehouses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_warehouses',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_warehouses_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='user_warehouses_warehouse_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_warehouses_pkey'),
    sa.UniqueConstraint('user_id', 'warehouse_id', name='user_warehouses_user_id_warehouse_id_key')
    )
    # ### end Alembic commands ###
