"""Add default UUID to UserWarehouse id

Revision ID: 98579fc715a4
Revises: 24562c11eb8a
Create Date: 2024-10-16 14:09:20.699033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98579fc715a4'
down_revision = '24562c11eb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('user_warehouses_user_id_warehouse_id_key', type_='unique')
        batch_op.drop_constraint('user_warehouses_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_warehouses_warehouse_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_warehouses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_warehouses_warehouse_id_fkey1', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_warehouses_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('user_warehouses_user_id_warehouse_id_key', ['user_id', 'warehouse_id'])

    # ### end Alembic commands ###
