"""Add org_username and org_password to organizations

Revision ID: a89fd50555cc
Revises: 98579fc715a4
Create Date: 2024-10-23 17:55:08.146423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89fd50555cc'
down_revision = '98579fc715a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('user_warehouses_warehouse_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_warehouses_user_id_fkey1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_warehouses', schema=None) as batch_op:
        batch_op.create_foreign_key('user_warehouses_user_id_fkey1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_warehouses_warehouse_id_fkey', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
