"""empty message

Revision ID: e127583f6ffd
Revises: c36c09c2027b
Create Date: 2025-12-25 12:22:45.309180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e127583f6ffd'
down_revision = 'c36c09c2027b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('warehouses_code_key', type_='unique')
        batch_op.create_unique_constraint('uq_organization_code', ['organization_id', 'code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_organization_code', type_='unique')
        batch_op.create_unique_constraint('warehouses_code_key', ['code'])

    # ### end Alembic commands ###
