# Generated by Django 6.0.2 on 2026-02-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('internal_admin', 'Internal Admin'), ('company_admin', 'Company Admin'), ('company_user', 'Company User')], default='internal_admin', max_length=20),
        ),
    ]
