# Generated by Django 6.0.3 on 2026-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_apply_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
