# Generated by Django 5.2.16 on 2026-08-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_can_apply_discount_user_max_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bound_device_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='device_bound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_label',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='device_lock_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
