# Generated by Django 6.0.4 on 2026-09-06 19:32

import core.ip_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_enable_device_lock_for_company_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedip',
            name='ip_or_network',
            field=models.CharField(help_text='IP Address or Network', max_length=50, validators=[core.ip_utils.validate_ip_or_network]),
        ),
    ]
