# Generated by Django 6.0.2 on 2026-02-25 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('identification_number', models.CharField(max_length=50, unique=True)),
                ('web_service_url', models.URLField(max_length=255)),
                ('web_service_username', models.CharField(max_length=255)),
                ('web_service_password', models.CharField(max_length=255)),
                ('employees_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.organization')),
            ],
        ),
    ]
