# Generated by Django 6.0.2 on 2026-02-26 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='web_service_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='web_service_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('organization', models.F('organization'))), null=True, related_name='warehouses', to=settings.AUTH_USER_MODEL),
        ),
    ]
