# Generated by Django 6.0.2 on 2026-02-26 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_web_service_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('organization', models.F('organization'))), related_name='warehouses', to=settings.AUTH_USER_MODEL),
        ),
    ]
