# Generated by Django 6.0.3 on 2026-03-11 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, default='', help_text='Optional label, e.g. "mobile", "work", "home".', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.customer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
