# Generated by Django 6.0.3 on 2026-04-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_copy_customer_to_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='customer',
        ),
    ]
