# Generated by Django 6.0.3 on 2026-04-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_normalize_organization_web_service_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerphone',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerPhone',
        ),
    ]
