# Generated by Django 6.0.4 on 2026-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organization_invoice_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invoice_template_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
