# Generated by Django 6.0.4 on 2026-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organization_invoice_template_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='recipient_first_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='recipient_is_different',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='recipient_last_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
