# Generated by Django 6.0.4 on 2026-05-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_purchaseorder_recipient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_retail',
            field=models.BooleanField(default=False),
        ),
    ]
