# Generated by Django 6.0.4 on 2026-07-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_organization_webhook_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogIngestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_full_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_delta_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_delete_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ok', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('received', models.PositiveIntegerField(default=0)),
                ('upserted', models.PositiveIntegerField(default=0)),
                ('deactivated', models.PositiveIntegerField(default=0)),
                ('images_failed', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_ingest_state', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('article', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=512)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('row_hash', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='core.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='uq_product_org_sku'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('product', 'barcode'), name='uq_barcode_per_product'),
        ),
    ]
