# Generated by Django 6.0.4 on 2026-07-12 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_name_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPushAllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_or_network', models.CharField(help_text='IP address or CIDR network allowed to push the catalog', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_allowed_ips', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'ip_or_network')},
            },
        ),
    ]
