# Generated by Django 6.0.4 on 2026-07-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_organizationpushallowedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('path', models.CharField(blank=True, default='', max_length=1024)),
                ('path_names', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, default='text', max_length=16)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='core.organization')),
            ],
            options={
                'ordering': ['order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='uq_attribute_org_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'external_id'), name='uq_category_org_extid'),
        ),
    ]
