# Generated by Django 6.0.4 on 2026-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gift_marking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
