# Generated by Django 6.0.4 on 2026-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organization_gift_marking_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='product_catalog_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='product_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
