# Generated by Django 5.2.16 on 2026-08-10 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_enable_catalog_for_orgs_with_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(43200)]),
        ),
    ]
