# Generated by Django 5.2.16 on 2026-08-10 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_organization_session_timeout_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(43200)]),
        ),
    ]
