# Generated by Django 6.0.4 on 2026-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_organization_session_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='retail_client_id_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='external_order_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
