# Generated by Django 6.0.4 on 2026-09-06 19:32

import core.ip_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_createorder_push_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpushallowedip',
            name='ip_or_network',
            field=models.CharField(help_text='IP address or CIDR network allowed to push the catalog', max_length=50, validators=[core.ip_utils.validate_ip_or_network]),
        ),
    ]
