# Generated by Django 6.0.4 on 2026-09-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_push_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invoice_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
