# Generated by Django 6.0.4 on 2026-09-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_organization_invoice_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_discount_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='auto_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
